  
### appspec.yml ####
version: 0.0
os: linux
files:
  - source: /
    destination: /home/developer/dockernodejs
permissions:
  - object: /home/developer
    owner: developer  ### Add user kalyan in the ec2 instances and we can deploy these file to the ec2-instances. Else codedeploy fails for not mentioning appropriate user in the appspec.yml file
    group: docker
hooks:
  BeforeInstall:
    - location: scripts/before.sh
      timeout: 120
      runas: root ## can run as root user also
  AfterInstall:
    - location: scripts/after.sh
      timeout: 120
      runas: root
